# Generated by Django 4.1.2 on 2022-10-18 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("breed", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=250)),
                ("age", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Feeding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "meal",
                    models.CharField(
                        choices=[("B", "Breakfast"), ("L", "Lunch"), ("D", "Dinner")],
                        default="B",
                        max_length=1,
                    ),
                ),
                (
                    "cat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main_app.cat"
                    ),
                ),
            ],
        ),
    ]
