# Generated by Django 4.1.2 on 2022-10-19 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_photos"),
    ]

    operations = [
        migrations.RenameModel(old_name="Photos", new_name="Photo",),
    ]
